# Generated by Django 4.1.4 on 2023-01-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('Usernumber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='ConQZ.user', verbose_name='学号')),
                ('CBindState', models.IntegerField(blank=True, default='', null=True, verbose_name='课程绑定状态')),
                ('CBindNumber', models.BigIntegerField(blank=True, default='', null=True, verbose_name='课程绑定学号')),
                ('GBindState', models.IntegerField(blank=True, default='', null=True, verbose_name='成绩绑定状态')),
                ('GBindNumber', models.BigIntegerField(blank=True, default='', null=True, verbose_name='成绩绑定学号')),
            ],
        ),
    ]
