# Generated by Django 4.1.4 on 2023-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0002_departmentclass_departname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentclass',
            name='departName',
            field=models.CharField(max_length=50, verbose_name='部门名称'),
        ),
    ]
