# Generated by Django 4.1.4 on 2023-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0002_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='CBindNumber',
            field=models.BigIntegerField(blank=True, default=-1, null=True, verbose_name='课程绑定学号'),
        ),
        migrations.AlterField(
            model_name='share',
            name='CBindState',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='课程绑定状态'),
        ),
        migrations.AlterField(
            model_name='share',
            name='GBindNumber',
            field=models.BigIntegerField(blank=True, default=-1, null=True, verbose_name='成绩绑定学号'),
        ),
        migrations.AlterField(
            model_name='share',
            name='GBindState',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='成绩绑定状态'),
        ),
    ]
