# Generated by Django 4.1.4 on 2023-01-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0003_alter_share_cbindnumber_alter_share_cbindstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groupname', models.CharField(default='', max_length=30, verbose_name='同好名称')),
                ('QQGroupNumber', models.CharField(default='', max_length=50, verbose_name='同好群号')),
                ('InfoContent', models.TextField(verbose_name='介绍内容')),
                ('LikesStatic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='同好群文件路径')),
            ],
        ),
    ]
