# Generated by Django 4.1.4 on 2023-01-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0004_likesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(default='', max_length=100, verbose_name='课程名称')),
                ('CoursePlace', models.CharField(default='', max_length=100, verbose_name='上课地点')),
                ('CourseTeacher', models.CharField(default='', max_length=20, verbose_name='教师名称')),
                ('CourseTime', models.CharField(default='', max_length=20, verbose_name='上课时间')),
                ('CourseWeek', models.CharField(default='', max_length=20, verbose_name='上课周数')),
            ],
        ),
    ]
