# Generated by Django 4.1.4 on 2023-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseTimeDict',
            field=models.TextField(blank=True, null=True, verbose_name='字典形式上课时间'),
        ),
    ]
