# Generated by Django 4.1.4 on 2023-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0006_course_coursetimedict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseTimeDict',
            new_name='CourseTimeList',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseWeekList',
            field=models.TextField(blank=True, null=True, verbose_name='字典形式上课星期'),
        ),
    ]
