# Generated by Django 4.1.4 on 2023-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0007_rename_coursetimedict_course_coursetimelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseTime',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseTimeList',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseWeek',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseWeekList',
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseTime', models.CharField(default='', max_length=20, verbose_name='上课时间')),
                ('CourseWeek', models.CharField(default='', max_length=20, verbose_name='上课周数')),
                ('CourseWeekList', models.TextField(blank=True, null=True, verbose_name='字典形式上课星期')),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConQZ.course', verbose_name='课程编号')),
            ],
        ),
    ]
