# Generated by Django 4.1.4 on 2023-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0008_remove_course_coursetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetime',
            name='CourseWeekList',
        ),
    ]
