# Generated by Django 4.1.4 on 2023-01-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0009_remove_coursetime_courseweeklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetime',
            options={'ordering': ('CourseId_id',)},
        ),
    ]
