# Generated by Django 4.1.4 on 2023-01-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConQZ', '0010_alter_coursetime_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CoursePlace',
        ),
        migrations.AddField(
            model_name='coursetime',
            name='CoursePlace',
            field=models.CharField(default='', max_length=100, verbose_name='上课地点'),
        ),
    ]
